### ISSUE TITLE
What is the current status of LokiJS2?

### ISSUE THREAD

**Issue by manndave** [LokiJS-Forge/LokiJS2#22]
Trying to determine if it is ready for use in a production app.

Thanks!

**Comment by Viatorus** [comment]
I just published a beta version at npm. Feel free to try it out. There will be some changes until release but nothing radical anymore.
The documentation is still missing but most of the api is the same like in LokiJS v1 (except promisfied database load/stores).

Thank you for your interest!

**Comment by Leftium** [comment]
Is there an ETA for the documentation/release?

Can you provide a simple example of using LokiJS2 with promises?

Is it as simple as this?

``` js
db = new loki('example.db');
await db.loadDatabase();
entries = db.getCollection("entries");
```

**Comment by Viatorus** [comment]
Yes, this should do it.

I tried to leave the API as is. As you already mention, all adapter calls: initializePersistence, loadDatabase, saveDatabase and deleteDatabase are returning a Promise.

Currently I still refactor the internal API by using TypeScript - only for type safety/member visibility - to get a better overview about the dependencies.
